SkyCryptWebsite/SkyCrypt

views/stats.ejs
Since the spreadsheet was discontinued, the link can be removed.
=> Removing link to accessories spreadsheet

src/constants/misc.js, src/lib.js
This code adds expertise_kills to the item lore including the amount of kills needed to the next Expertise level.
(This has been almost fully tested (exept for the case with a maxed rod with over 15000 kills, but I'm prettyconfident that works too)
=> Expertise kills

src/constants/misc.js, src/lib.js, views/stats.ejs
This adds the minion slots from the profile upgrades to the Minions section,
(This also adds all 5 profile upgrades to the profile object even thogh 4 of them are unused for now)
EDIT: now it also adds the profile upgrades to the misc section.
The bonus minion slots are now in 2 sections (minions and profile upgrades). 
Question is if the Profile upgrades one should be deleted or if it should stay there
=> new minion slots and all five profile upgrades

public/resources/js/stats.js
run scrollbar detection in `load` instead of `DOMContentLoaded`
see #74 for more info
=> run scrollbar detection in later

public/resources/css/index.css
this PR stops the user from accidentally scrolling the main page when hovering over the popup that appears after clicking on an item
=> prevent overscroll bubbling on stats popup

public/resources/css/index.css
87% of browsers support `backdrop-filter` according to [caniuse](https://caniuse.com/?search=backdrop-filter).
This CSS property allows us to add background blur without the need for a second picture.
This PR uses `backdrop-filter` on browsers that support it meaning that the browser doesn't need to fetch the pre-blurred image.
On browsers that do not support `backdrop-filter` (Firefox), the page will fall back to the old system.
=> use backdrop-filter instead of --bg_blur-webp when supported

includes/resources.ejs, public/resources/css/index.css
Small css change to add 1rem margin between enderchest pages to improve readability.
Here's the result:
=> Add margin between enderchest pages

src/constants/pets.js, src/lib.js, views/stats.ejs
PR to add support for pet skins:
Visible skins in the pets section
Added statistics for unique pet skins
Added skin name in the first line of the lore (same as in-game)
Full preview: https://i.imgur.com/6RtFpRu.png
Current SkyCrypt: https://i.imgur.com/aCLTCwX.png
I would just note that unfortunately I do not own all the skins so I am unable to test:
- ~~Pink Sheep~~ tested, works
- ~~Smiling Rock~~ tested, works
- ~~Derpy Rock~~ tested, works
- ~~Embarrassed Rock~~ tested, works
- ~~"golden-text" counter for "Unique Pet Skins"~~ tested, works
But everything should work fine (unless there's some name mismatching between the skin item and the pet skin id).
Hopefully this time I made the PR correctly 🤞
=> Added pet skins (cleaned)

src/constants/misc.js
New titanic accessory bag upgrade (45 -> 51 slots)
=> Added Titanic Accessory Bag upgrade size

views/stats.ejs
as discussed in [this article](https://v8.dev/blog/cost-of-javascript-2019#json) browsers parse JSON faster than Javascript so by sending constants to the client as a string with `JSON.parse()` loading times can be reduced
=> Improve performance with json.parse

src/constants/pets.js, src/lib.js
Player: Bot4He
Before:
After:
Basically pet_items can now have a new property "multAllStats: Float" that multiplies all the stats of a pet.
In libs.js the only real addition is:
```js
if ('multAllStats' in constants.pet_items[heldItem]) {
for (const stat in pet.stats) {
pet.stats[stat] *= constants.pet_items[heldItem].multAllStats
}
}
```
everything else is just code formatted with parenthesis so that I could understand it more easily.
=> minos_relic support

src/constants/petStats.js
PR mainly to fix sheep pet stats (from 50 ability damage to 20%)
In game:
SkyCrypt:
PR:
I removed the ability_damage param from formatStat() since it wasn't used
Also sorted the pet stats export to match the correct pet types (jerry -> combat, guardian -> enchanting)... nothing important but I saw that and so... 🤷‍♂️
=> Pets minor fixes (sheep stats, ability damage suffix)

views/stats.ejs
https://sky.shiiyu.moe/stats/El_Oxo/Grapes
From:
To:
Honestly it's not a big change but I always found it annoying.... but I agree that having 1 more decimals outside might not please everyone so I think you should vote on this one and then decide what style you prefer.
=> Average skill level to 2 decimals to fix rounding issue

src/constants/petStats.js
Bug report:
Checked the pets in game and fixed the missing ferocity (if you need screenshot as proof of every pet let me know).
=> Fix missing ferocy stat on a bunch of pets

views/stats.ejs
I added it visible by default, I don't know if it should be hidden (and visible after clicking the ">" arrow)... I feel like there's a lot of links now; maybe we should hide some based on how often they are used? (do you have stats about this?)
=> NameMC link in profile

includes/resources.ejs, public/resources/css/index.css
Fix for navbar overflow reported by minhperry.
He's using a vietnamese browser that causes this issue **_but_** I noticed this issue also in chrome at smaller resolutions (see screenshots below)
The fix simply makes the navbar always scrollable horizontally if it needs more horizontal space.
Bumped css version from 144 to 145
VSCode automatically fixed random spaces after some css properties
Actual css fix is at lines:
L3577-L3582: removed the old media query
L1509: permanent `overflow-x: scroll`
PS: Please do something about code formatting, it's a pain seeing random formatting, code indentation and spaces everywhere ;-;
=> Fix navbar overflow

src/constants/pets.js, src/lib.js
Hardcoded pet items name and tier to be used as a fallback in case the local db doesn't have the item saved.
=> Pet items fallback in case they are not in the db

src/constants/petStats.js
In my previous PR I didn't notice that making Jerry mythic also changes his 3rd perk multiplier:
=> Jerry pet damage fix when mythic

includes/footer.ejs, public/resources/js/stats.js, src/helper.js, views/stats.ejs
This was caused by the fact that, in petStats, the Lion class per description doesn't start with a formatting § character.
the renderLore() then splits the text by § and gets the first character to transform into a color, if the color is undefined it skips the part:
```js
for(const part of parts){
const code = part.substring(0, 1);
const content = part.substring(1);
const format = constants.minecraft_formatting[code];
if(format === undefined)
continue;
```
The fix simply adds a default gray color at the beginning `§7`
renderLore() was defined in 2 files: stats.js and helper.js, changed how it works in both.
The function seems to be used only to render petLore (now works), item lore (that should always start with a § anyway, so nothing changed here), and guild tag. For the guild tag case I …
=> renderLore() fix in case the string doesn't start with a formatting §

src/constants/pets.js, views/stats.ejs
Support for new Golen Monkey skin.
Every pet_skin now has a release property (timestamp in milliseconds) which represent when it was first released in skyblock, this will be used to correctly display the "Unique Pet Skins" counter/stat above pets.
Please note than I'm lazy and instead of putting the correct timestamp for every pet I used skyblock release time for all the old pets 😛
=> Golden monkey skin + keep the unique pet skins counter correct until new skin release

src/constants/talismans.js
They made the heads using transparent pixels, and skycrypt head renderer actually renders transparent pixels.... but in game they are black:
I'm not sure if this is something we should look into or just ignore
Anyway here's a preview with the real skins used in game:
=> Titanium accessories

views/stats.ejs
The code for calculating max minions was updated in the overall stat above but not in the skill sub-category
Before:
After:
=> Fix: max minions not counted towards max minions in skill sub-category

public/resources/scss/index.scss
this PR fixes a mistake I made in #250
=> fix slayer bar styling

includes/footer.ejs, public/resources/js/stats.js
this PR fixes a bug reported by @sav#2222 on discord.
there are three fixes in this PR:
- backpacks with more than 27 slots no longer fail to preview
- backpacks with more than 27 slots are no longer broken up into pages
- there is no longer extra space on some inventories with full pages
=> Fix large backpacks

public/resources/scss/index.scss
if you hover over an item it SkyCrypt shows some info but if you accidentally hover over the number of items in the stack (`.item-count`) then the info goes away. This PR fixes that
note: if this PR is merged it will not take effect for most users until something increments the index.css version on resources.ejs line 13 but it also won't hurt anything if the index.css version is not incremented
=> fix hover on item stack

.github/workflows/stale.yml
according to https://github.com/actions/stale/blob/main/README.md the message feilds are optional and removing them would alow us to use the default rather than the current unhelpfull message
=> remove optional feilds

includes/footer.ejs, includes/resources.ejs, public/resources/scss/api.scss, public/resources/scss/index.scss
on iOS, the background is zoomed in and scrolls with the page. this is because iOS doesn't support `background-attachment: fixed;` to work around this I have added an alternative way of getting a fixed background for iOS devices.
=> fix iOS background

includes/resources.ejs
this PR addresses a minor inconvenience reported by `Obese Microwave#0451` on discord.
autocorrect on mobile will sometimes add a space after some works which is then converted to an underscore by the server.
trim extra whitespace from the form input.
this will make it slightly harder to type username with underscores at the end or beginning on mobile
=> trim input on client side

public/resources/js/stats.js, public/resources/scss/index.scss, views/stats.ejs
this PR redoes the way that an element is flashed when it is updated by selecting a different weapon so that the anime dependence is no longer needed for it and it uses CSS instead of js so it should run smoother.
eventually, anime can be removed if [scrollIntoViewOptions](https://caniuse.com/mdn-api_element_scrollintoview_scrollintoviewoptions) ever becomes widespread
=> Better flash

includes/footer.ejs, includes/header.ejs, includes/resources.ejs, public/resources/js/stats.js, public/resources/scss/index.scss, views/stats.ejs
this PR redoes the way margin and padding are put on the right and left side of the stats page. this two main effects:
1. the overall layout of the stats page should be easier to maintain
2. iOS landscape looks way better
this PR also fixes several longstanding visual bugs with the info, themes, and packs boxes
=> better iOS landscape

public/resources/scss/index.scss, views/stats.ejs
Uses grayscale colors for skills when skills API is disabled (+ 0.5 opacity) and removes the avg skill.
(+ fixed the css selector for the ".no-access" text)
(+ my editor fixed random extra spaces in the .ejs file)
Before:
After:
=> Styles when a user has skills API disabled + hides skill avg

public/resources/js/stats.js, public/resources/scss/index.scss, src/helper.js
this PR turns Obfuscated text (`§k`) into solid blocks of color and also fixes a minor bug where only the last formating code was being recognized
=> Obfuscate text

src/constants/minions.js, views/stats.ejs
before
after
Also the total unique minions is hardcoded.... maybe it shouldn't, but for now it works I guess?
=> revenant t12

src/lib.js
So after the introduction of rev5 slayer and the updated rewards they added 3 new claimed rewards keys in the API:
This PR makes it so the `level_7`, `level_8` and `level_9` for zombie gets ignored and only the specials one will be used to determine if the user has claimed the rewards.
=> fix zombie unclaimed rewards

src/lib.js
Added the % progression (0 to 100) on pets tooltips:
Also I decided to let it go above 100% because some people (like me) can find it useful or nice to see.
=> pet exp progression

src/lib.js, views/stats.ejs
Pets section update:
- Includes the pets found in inventories (inventory, enderchest, etc...) in the pets section. It converts the real item object into a pet object like all the other pets (to make sure they all look the same).
- Shows max 100 pets (like in skyblock, when you can add max 100 pets in the pets menu). After 100 the pets are added in an expandable section "Show More Pets".
- Added a variable that controls the limit on the max number of pets to show (currently set to 250); this is to prevent pet spam.
- Rewrote how the pets are printed in `stats.ejs`.... just feels more organized now
=> Pets section update (show pets in inventories, show max 100)

includes/header.ejs, includes/resources.ejs
instead of supplying a bad experience to users with no javascript we just ask the user to enable it ![localhost_32464_(iPad)](https://user-images.githubusercontent.com/44071655/112407032-b2ce4d80-8ceb-11eb-8aa7-2885a3bb2beb.png)
=> remove suport for browsers without javascript

src/lib.js
It will make it easier to understand what the kills and deaths really are for, instead of having to guess at what it could be.
Sadan Statue => Terracotta
Obsidian Wither => Obsidian Defender
=> Rename certain mobs to reflect in-game names

src/lib.js
This will fix the current issue with profiles who played master_catacombs to have weight NaN.
The weight calculator uses the xp accumulated for each dungeon to calculate its weight, the problem here is that master_catacombs it's not actually a new dungeon, but instead an extension of catacombs (the xp gained goes to catacombs, not master_catacombs).
This fix simply adds a check if the dungeon is a "master" and simply returns 0 for the weight (that will be added to the total `calculated.dungeonWeight`.
There's a chance Senither will will do it differently, and in that case we update the code; but until then this fixes the NaN issue.
=> Fix master catacombs weight

includes/header.ejs
make image icons in the packs and themes selectors not load until the user opens the selector this will result in a very small performance gain
=> lazy load pack icons and theme logos

public/resources/scss/index.scss
this PR uses `overflow: clip;` to improve performance and fix [a display bug](https://discord.com/channels/738971489411399761/738990246825427084/831453770482712646) on browsers that support it (Chrome and Firefox) this PR doesn't affect other browsers (Safari and old Chrome versions) at all because they will just fall back to `overflow: hidden;`
=> overflow clip

src/constants/misc.js, src/lib.js
As in title Renowned reforge and Superior 5% most stat boost no longer boosts:
- Mining Speed
- Mining Fortune
- Farming Fortune
- Foraging Fortune
=> Renowned & superior all stat boost no longer boosts mining speed and skill fortune

src/constants/petStats.js, src/lib.js
fixes #389 
Please note that I removed the check if the user has been offline for at least 7 minutes. I'm not sure why this was implemented in the first place, maybe because if the player is online the armour already has the correct stats? But running it either way doesn't cause any issue so... why not
=> fix blaze no armor error

src/lib.js
There are now 227 fairy souls as of Skyblock 0.11.4
=> Update max fairy soul count

views/stats.ejs
- "Missing Talismans" -> "Missing Accessories"
- Added a space after expanding the missing accessories
Before:
After:
=> spell fix: missing talis to accessories

public/resources/js/stats.js, public/resources/scss/index.scss, src/constants/petStats.js, src/lib.js
This PR left justifies the lore text and stops pet item lore from being too wide.
Before:
After:
=> lore left justify and pet lore wrap

src/lib.js
Basically when we use `item.type === 'accessory'` we also need to check for it's dungeon type variant `item.type === 'accessory' || item.type === 'dungeon accessory'`.
This PR adds the missing dungeon variant everywhere it was needed.
This PR also removes the looting enchant from the workaround to detect the item type since looting can be found in more than 1 item type.
=> Fix item.type to include dungeon variant in lib.js

src/constants/petStats.js, src/lib.js
Fixes #446 
- Add comments to Blaze pet that indicates the modifyArmor() is required for offline players
- Removed Zombie pet modifyArmor() since it's not required (armor stats are correct even when the player is offline)
- Added the dungeon types variants when executing the modifyArmor() function
=> Fix modify armor

views/stats.ejs
the video that shows how to use the api is downloaded every time a user visits the site but this PR makes it so that the video is only downloaded when the user wants to watch the video
=> lazy load enable api video

public/resources/scss/index.scss
=> fix light theme bonus divider

src/constants/petStats.js
Added the enderman pet's mythic ability which grants 0.4% more combat xp from endermen per level. "xp" and "endermen" are not capitalized in the ability in game.
=> Add mythic enderman pet

public/resources/scss/index.scss, views/stats.ejs
this PR refactors how `.narrow-info-container` layout works and cleans up the enderman slayer a bit
=> Enderman slayer fix and `.narrow-info-container` refactor

CONTRIBUTING.md
because it's easier for beginners due to its integration into the GitHub website
=> Recommend GitHub Desktop instead of GitKraken

public/resources/scss/index.scss, src/constants/misc.js, views/stats.ejs
This PR does 3 things:
- remove average drops
- refactor slayer styles (using the grid for kills)
- remove unused constants from `stats.ejs`
=> remove slayer drops

.github/workflows/node.js.yml
the name of the CI workflow is long and redundant this PR shortens it to "CI"
this PR also adds Nate's name to the workflow so you can blame him when it breaks
this PR also fixes the spelling of the prettier job id
before:
after:
=> change  name of CI workflow to "CI"

views/index.ejs, views/stats.ejs
- removes "an" from "an API maintenance"
- change "user's" to "users'" because more than one user
- put only one `<br>` per line
- use `<strong>` instead of `<b>` for improved accesablity
=> grammer and accesablity

views/stats.ejs
this PR fixes some refrances to non-existant varables
before:
after:
=> make farming crops work

public/resources/scss/index.scss, views/stats.ejs
this PR requires #575
This PR unifies collections, minions, boss collections, farming crops, and experiments all into one class called chip
this new class looks basically the same but uses CSS grid and flex for m modern flexible layout
additionally, the following things were changed about chips
- icons increased from 42px to 48px
- padding increased from 7px to 8px
- farming crops and boss collections now become horizontal scrollers on mobile
this PR also removes the white lines between experiments
before:
after:
before:
after:
=> Chip CSS refactor

public/resources/scss/index.scss, public/resources/ts/stats-defer.ts, views/stats.ejs
This PR removes the div with the `piece-hover-area` class
instead a ::after element is used
this PR also removes the hover effect from devices that cannot hover
this results in having fewer elements on mobile which should lead to a small performance improvement
=> remove .piece-hover-area

views/stats.ejs
This PR adds a timestamp tippy tip and refactors a few things to avoid extra spaces
=> add hover time to dungeon timestamp

includes/header.ejs, public/resources/ts/common-defer.ts, public/resources/ts/globals.d.ts, public/resources/ts/themes.ts
The goal of this PR is to add a very small blocking script to load the theme before the dom content starts loading
this PR adds the interface `ProcessedTheme` which contains a theme that is ready to be applied in as little code as possible
by storing processedTheme in localStorage we can load the theme quickly when the page is loaded and do all the processing when the user changes the theme
=> store processed theme in localstorage and load it in blocking script

src/app.js
before rollup runs it deletes everything in the output directory this update was triggering nodewatch wich would try to read a nonexistent file.
this PR fixes the problem by ignoring nodewatch when the file is being removed
=> fix file does not exist error in dev

public/resources/ts/stats-defer.ts
this PR fixes a bug that was causing the lore to open when the user changed the selected weapon/rod
=> stop selecting item from opening lore

src/app.js, src/constants/petStats.js, src/constants/pets.js
**This PR includes the changes made in #643, so merge that first**
---
Fixes #619 
This is still a work in progress, but at the very least it adds the head texture and the basic perks and stats of the pet (it can be merged).
What's left to be done:
- Support for different name and skin when level is < 100 (pet still hatching)
- Support for xp progress up to level 200 (we don't have the values yet)
- Actually have screenshots of this pet in game to confirm the stats/perks before and after hatching
=> Golden Dragon

src/loreGenerator.js
this PR removes some unused data from armor
=> remove `item.tag.display.lore` because it is a duplicate of `item.tag.display.Lore`

views/api.ejs
I can't run localhost to test this but it should work
=> fix: make api page work when no theme is set

public/resources/scss/index.scss, src/lib.js, views/stats.ejs
This PR:
- Adds a small red `!` next to weight if one of the 3 weights failed to calculate.
- Formatted the code that was printing the Weight stat and tooltip.... turns out there was an extra `</span>` there lol
- Fixes a bug where if a player never played a class, their entire dungeon weight will be Error.
The issue was caused by the player_classes looking like this:
I first tried to skip calculation for classes never played, but all the code after it and in frontend expects the resulting object to have all the classes so I ended up manually setting experience=0 for the never played classes.
Ref
=> fix dungeon weight calculation error

views/stats.ejs
rename Weight to Senither Weight so that when we add Lily Weight it will be clear to users which was the old one. This also avoids confusion with the lily weight used on skylea
this is a ejs only change so a server restart is optional
=> label weight as senither weight

src/app.js
this PR makes 3 cache settings and groups all cached assets into one of these
used for hashed assets as recommended by google and others
used for things that will probably not change and if they did change it would be ok if the user gets an old version
used by capes because they could change any time but it's ok if they are a little outdated
before this PR some `max-age` was set to 100 times more than it should have been because of confusion between seconds and milliseconds
=> change/fix Cache-Control max-age

public/resources/scss/index.scss
this PR adds grey background to items with no valid rarity
Before:
After:
=> add fallback for item-name background

public/sw.js
currently, the service worker replaces index and stats pages with the offline page when offline
this PR makes it respond to any navigation requests, not just index and stats
=> respond with offline url based on navigation type not url

src/api.js, src/apiv2.js, src/helper.js, src/lib.js, src/renderer.js
in this PR I refactor code so that it doesn't use the `getPath`, `hasPath`, and `setPath` helper function I replace these with modern vanilla js future like optional chaining and the `in` operator.
the only remaining uses of these functions are the lines where an array is being exploded into the function
I did not modify `api.js` because it is outdated anyway
=> less `getPath`, `hasPath`, and `setPath`

public/resources/scss/index.scss
Just adding `?v2` to all stats icons for cache busting
Didn't test... I can't test, I don't have the old images in cache
=> cachebusting stats icons

includes/footer.ejs, package-lock.json, package.json, public/resources/scss/index.scss, public/resources/ts/common-defer.ts, public/resources/ts/stats-defer.ts, rollup.config.js
This PR makes tippy an npm dependency instead of using the CDN. this allows us to tree shake and also means that the browser doesn't have to open an extra connection. it also means that dependabot can update tippy now.
This PR also updates from tippy 5 to tippy 6
=> Import Tippy 6 directly

src/apiv2.js
Our API should've been cache-only all along, so this fixes the issue of API requests using external resources.
This bug was created by a commit from me from April 19th, _sorry for that one_.
=> Fixed API caching in /apiv2

src/apiv2.js
There were still some unintended external requests after previous PR, so here we have another PR that attemps to fix it. 
Right as I were adding cacheOnly into other methods used in the API, I went ahead and simplied it using an options object, that contains some things the methods use for caching and debug stuff.
_Let's hope it works this time.._
=> Fixed more things around API caching

src/helper.js
Closes #790 
Adds support for Mining, Combat and Defensive gemstone slots types on top of Universal and gem specific ones
Fixes https://sky.shiiyu.moe/stats/snapdoomy `TypeError: Cannot read property 'color' of undefined`
⚠️ I could not find any profile with a MINING slot being used, so that's not tested (and I do not own a X655 or Divan Drill)
=> New gemstone slots support (defensive, combat, mining)

src/constants/gemstones.js
This fix requires #808 to be merged (since that PR adds support for Divine rarity)
Basically added the few known stats of gemstones on divine rarity (based on DeathStreeks Divan's Drill), also changed the main comment again so that `null` values are to be considering "unknown value" which is honestly more correct.
Added `null` on everything unknown, I could've left it empty but this way is easier to spot missing values for future updates.
=> (fix) Some gemstone stats for divine

src/constants/pet-stats.js, src/constants/pets.js, src/lib.js
Support for new Quick Claw pet item:
pet items now can have a new property `statsPerLevel` to make this new pet item work
Closes #792
=> Quick claw

src/helper.js
Fixes `TypeError: Cannot read property 'color' of undefined` for:
- https://sky.shiiyu.moe/stats/TheDarkKillerGR
- https://sky.shiiyu.moe/stats/15h
Basically yesterday I didn't knew `OFFENSIVE` was another type of special slot, but I also noticed there's a new key for only the new items in `ExtraAttributes.gemstones.slots_unlocked` that needs to be ignored while parsing the gems.
So I just went ahead and refactored the function a bit, now it's much more cleaner and should also give a straightforward error message in case new unknown keys appear.
=> fix: parseItemGems refactor

src/constants/minions.js, src/lib.js, views/stats.ejs
wowo metal actually contributing
this pr edits the `minions_max_uniques` constant to automatically calculate how many unique minions a user can craft
it also has a fix for #730
=> Remove hardcoded minion count

src/helper.js
This temporarily solves the issue, but I would like some feedback.
Basically in game there's some DIVINE rarity items that aren't supposed to exist, mostly dungeon armor like Necron or Shadow Assassin, example:
https://sky.shiiyu.moe/stats/Bucklez/Coconut#Armor
What I think happened is that admins didn't expect/know this items existed so they didn't code in the values for DIVINE stats in gemstone that can't be applied to Divan's Drill (the only item that should have DIVINE rarity as of right now).
In game that item gems use the value as if the item was a a mythic rarity, so as a temporarily solution I coded that if the item is DIVINE and we are missing the gemstone stat value it tries to fallback to MYTHIC.
What do you think?
Instead of doing this we could just hardcode the "fake/temp" …
=> Fallback divine gemstone stats (feedback?)

src/constants.js, src/constants/armor.js, src/lib.js
Ok so basically someone reported this:
one thing got to another and... well refactored half the code of armor_set.
Now:
- it should be much easier to understand
- the bug has been fixed
- armor_name ignores master stars ⍟ and skin ✦
- armor_name converts directly *piece name* to Armor
- special sets of armor have been moved to constants/armor.js
- armor_set_rarity now calculates the highest rarity of the armor set instead of just using the boots rarity
- support for all armor sets added in the past 2 years... yeah this code was quite outdated
Only feature lost is if you are wearing different tiers of Perfect Armor, before it would display "Perfect Armor" while now it doesn't display anything. I prefer it this way so I don't have to hard-code anything specific in lib.js.
I tested this …
=> armor_set refactor with some bug fixes

src/constants/hotm.js
Fixes a couple issues with HotM:
- Quick forge at level 20 goes up by 10.5% instead of the normal 0.5% (so level 18 is 19%, 19 is 19.5%, 20 is 30%)
- Change the lore of the reset when user hasn't used the free reset yet
- Upgrade costs are now formatted (before: `123456`, after: `123.456`)
=> Hotm fixes

src/lib.js, src/weight/lilyWeight.js, views/stats.ejs
this PR changes `calculateLilyWeight` to use `getWeightRaw` instead of `getWeight`
=> Fix lilyweight

package-lock.json, package.json, rollup.config.js
this PR adds a rollup plugin to remove extra whitespace in HTML string literals
before:
```js
`<div class="view-backpack" @click="${() => showBackpack(backpack)}">
<span>View Backpack</span>
<small>(Right click backpack to immediately open)</small>
</div>`
```
after:
```js
`<div class="view-backpack" @click="${() => showBackpack(backpack)}"> <span>View Backpack</span> <small>(Right click backpack to immediately open)</small> </div>`
```
=> minify HTML literals

src/constants/hotm.js, src/helper.js
Fixes missing color format here:
Adds `ceil()` function exported by helper.js
Changes all `Math.ceil()` into `ceil()` in hotm.js
Updates/fixes EfficientMiner formula (before it wasn't calculating the amount of blocks correctly)
=> Hotm fixes 2

src/constants/bonuses.js, src/constants/leveling.js, src/constants/weight.js, src/lib.js, views/stats.ejs
Adds support for social skill, but it's not being displayed (`skill_component()` commented out) since the API seems to be returning wrong values.
For my profile it doesn't even return the `experience_skill_social` key, even though I'm level 12. Same for Nate and Lea profiles.
For metalcupcake it returns a value, but it's far from the real value in game (returned value is level 2, in game he's level 11)
Merge anyway in case it will be fixed in the future?
=> Social skill

src/constants/forge.js, src/lib.js, views/stats.ejs
This PR does 2 things:
1. Closes #942 by adding the times for the new recipes
2. Changes the HTML so that it only uses 1 `<span>` instead of 2 and also uses the correct `stat-value` class instead of `stat-raw-values` which is correctly vertically aligned (and it's what we usually use everywhere else)
3. Adds a fallback in case of future new items, so the forge processes won't look like this:
old:
new:
---
PS: The name is parsed by items collection so it will get fixed soon, whenever builder's API updates
```js
const dbObject = await db.collection("items").findOne({ id: item.id });
forgeItem.name = item.id == "PET" ? "[Lvl 1] Ammonite" : dbObject ? dbObject.name : item.id;
```
next day edit:
there they are
=> forge processes unknown and scrolls

public/resources/ts/stats-defer.ts
by using passive listeners we promise the browser we will never use `.preventDefault()` on the scroll event so the browser can scroll for the user before it is done calling our code. this should result in smoother scrolling for users with slow CPUs.
=> use passive scroll listeners

src/lib.js, src/lore-generator.js
basically the function `makeLore()` that updates the item Lore when an active pet modifies the armor `activePet.ref.modifyArmor()` had a `.slice(5)` that should be a `.slice(3)` instead.
Also added a few comments to hopefully help in case someone in the future has to go through these functions again... and removed the outdated "HP" in the generated lore
I honestly have no clue why it was 5, if it was correct before but wrong now or what... but with 3 it seems to be working fine now
Edit: I know why it was 5:
Health with HPB used to contain the words HP on the health value and in the parenthesis... now it doesn't anymore so the split contains less items... so it's correct that it is 3 now and before it was correct that it was 5
=> fix makeLore to show correct stats for Health

views/stats.ejs
Crystal Hollows Pass now lasts 5h, instead of 2h... the tooltip while buying it is still outdated in game though.
=> crystal hollows pass 5h

src/custom-resources.js
didn't realize my PR that added a `README.md` in the resourcepack folder with instructions on how to add new/update resourcepacks added this warning.... this fixes it by ignoring files in the `/public/resourcepacks/` folder
=> Fix "Couldn't find config for resource pack README.md"

includes/header.ejs, public/resources/scss/shared.scss, src/weight/lily-weight.js, views/stats.ejs
Changes:
- Uses github repo link instead of npm package for lilyweight attribution
- Updates the meta description to include lily weight (preview below)
- Changes the emoji used for `Avg Skill Level` in meta description so discord doesn't see it as a character but rather an emoji like the others (maybe it's just a windows thing, idk)... we are still discussing in discord which emoji to use so it might change later
- Changes the tooltips for weights and rounds the value to 0 decimals (the 2 decimals value can be now seen in the tooltip)
- Fixes an issue that caused profiles that never entered dungeons to return a TypeError (see changes in `lily-weight.js`)
Meta description:
```text
❤️ 2980 🛡️ 1088 💪 1054 🌀 121% ☠️ 840%
🧚 227/227 Fairy Souls
🗡️ Fabled Atomsplit Katana
🌾 Farming 60
🔥 …
```
=> Weight systems fixes

public/resourcepacks/FurfSky_Reborn_1_4_2/assets/minecraft/mcpatcher/cit/item/weapons/normal/melee/reaper_scythe/reaper_scythe_revenant.properties
Closes #981 
Fixes the issue caused by a generic .properties file of FurfSky Reborn 1.4.2 matching all diamond hoes as Reaper Scythes.
Thanks Erymanthus | u/RayDeeUx for the help!
Discord thread: https://discord.com/channels/738971489411399761/911036781661679656/911643519813320725
=> fix furfsky reborn 1.4.2 reaper scythe

views/stats.ejs
this refactor makes it so that code is not duplicated between lily and senither weight
this PR also fixes a problem where an extra space is added between the weight number and the tippy `*`
this PR removes the word "provided" from weight attribution so that it will all fit on one line
this PR also makes the weight round instead of floor because everyone likes bigger numbers :)
=> Refactor weight systems

includes/resources.ejs, public/resources/ts/development-defer.ts, public/resources/ts/stats-defer.ts, rollup.config.js
This PR adds `development-defer.ts`.
In `development-defer.ts` we can add various things useful for developers, this file is only loaded when the website is launched in development (`npm run dev`).
Currently it adds 2 things:
- A `console.log()` message to let the developer know they are in development mode
- The ability to `alt+click` on any `.rich-item` on the page to `console.log()` the item object (very useful for debugging resource packs!)
=> SkyCrypt Dev Mode - Alt+click .rich-item to console.log the js item object

public/resourcepacks/FurfSky_Reborn_1_4_2/assets/minecraft/mcpatcher/cit/uielements/skyblock_menu/hotm/complete/fortunate.properties, public/resourcepacks/README.md
The HotM perk "Fortunate", when maxed, was missing the texture due to how the `.properties` file matches the GUI item:
asked in discord and there's a good reason to why they do this ([link](https://discord.com/channels/738971489411399761/911990892347416646/911994728109703239)) ... but this means we need to manually update this every time we update FSR pack.
This PR:
- Fixes the issue by manually updating the `.properties` file
- Adds a section to the `public/resourcepacks/README.md` to keep track of the files that need manual changes when updating the resource packs.
I thought if there's a way to automatically detect and fix this but I couldn't think of any (even ignoring the color codes in the name wouldn't be enough)
=> fix furfsky reborn fortunate perk

src/custom-resources.js
Fixes #978 
---
Ok so, `custom-resources.js` was bugged. I'll try to explain the bug...
For each texture the JS was checking if the value was matching the regex pattern specified in the .properties file... 
Example (`value`=ipattern:`regex`):
`nbt.display.Name=ipattern:*Mole*`
`nbt.display.Lore.*=ipattern:*Level 1*`
if it was matching it would increase the total number of matches by 1... at the end if the total number of matches was === to the number of values:regex to check, then the texture was a match for the item.
So where's the issue? in the Lore.
The code was checking if the regex was matching for **each line** of the Lore, so if the Lore matched 2 times, it would increase the total matches by 2... meaning that if we had 2 values, 1 failed but the Lore matched 2 times, the total …
=> fix custom resources non-breaking loop

src/constants/hotm.js
Found by rainbowcraft2:
turns out we had the wrong cooldowns for Pickobulus ability
=> fix pickobulus cooldown times

public/resources/ts/common-defer.ts, public/resources/ts/stats-defer.ts
fixes 2 eslint warnings
`substr()` -> `substring()`
`unescape()` -> `decodeURIComponent()`
=> Fix Eslint warnings

src/constants/bonuses.js
adds the bonus stats that enderman slayer gives
Before(LeaPhant/Grapes, currently eman 4):
After:
=> enderman slayer bonus stats

public/resources/scss/shared.scss, src/constants/misc.js, src/helper.js, src/lib.js, views/stats.ejs
Description:
Pretty much does exactly what the screenshot shows. 
It adds the completed race speed tiers from the objectives api.
~~Sidenote: 
Converting the objective names into the race names, I didn't know what would be uglier. Coding in the few edge cases that tere are or making a lot of dictionary entries... for now I chose the first option - in hindsight the second option would have been better, but I want to hear your opinion on the implementation first.~~
EDIT: changed it to the second option
=> added the speed tiers reached in the races

public/resources/ts/globals.d.ts, src/lib.js, src/weight/senither-weight.js
Player `VedatsGT` reported that senither weight was wrong for his profile.
Basically the player has enough farming xp for level 60 but he only has unlocked up to level 53.
Senither weight ignoes the in-game unlockable level caps so it always calculates as if max level for farming is 60.
I had to introduce `unlockableLevelWithProgress` (if you have a better name for it lmk) which is a value in `Levels` which returns the user level ignoring the unlockable in-game caps, with progress (cause senither wants progress).
`uncappedLevel` can't be used because it returns values as if the max level was 60 for everything, but alchemy is still considered max level 50 for senither (same as in-game).
so now we have:
- `level`: player level considering level cap and unlocked in-game caps.
- …
=> Fix wrong senither weight if farming level < uncapped level

.eslintrc, public/resources/ts/common-defer.ts, src/app.js, src/helper.js, src/lib.js, views/index.ejs
it is generally good practice to throw instances of `Error` and not strings. This PR makes this change and adds an eslint rule to prevent regression.
=> always throw Errors not strings

src/constants/dungeons.js
changes sa chestplate in livid collection to a different name so it shows as claimed
before([VedatsGT](https://sky.shiiyu.moe/stats/VedatsGT/Kiwi#Slayer))
after
=> fix livid dungeon colelction
