SkyCryptWebsite/SkyCrypt

- src/helper.js
v2 currently breaks username loading as it returns 404 for every request
> Swich to ashcon v1 to solve issues

- public/resources/css/index.css
- public/resources/js/stats.js
- src/constants/misc.js
- src/constants/talismans.js
- src/lib.js
- views/stats.ejs
Add a basic missing talismans display. Currently displays talismans you have a higher upgrade of, working on a fix soon
> Finalize basic missing talismans display

- includes/resources.ejs
I think this is the best of both worlds
its readable and it uses ternary
> make the method cleaner and also short

- src/lib.js
Lower talismans in a specific line that you already have don't appear in missing talismans. Solves #19
> Don't include lower teir talismans in missing list

- src/constants/misc.js
https://github.com/SkyCryptWebsite/SkyCrypt/issues/28
> added some spec enchs

- src/constants/misc.js
Reverts SkyCryptWebsite/SkyCrypt#29. I'll re-add the special enchantments in another commit
> Revert "added some spec enchs"

- misc/nginx/scripts/apistats.py
> Clean up API Stats

- src/constants/petStats.js
- src/constants/pets.js
Added the pet description to the website. It's only missing a texture.
> Added the megalodon pet

- public/resources/api/api_docs.json
fix typo in enpoints to endpoints
:shipit:
> fix enpoints

- public/resources/css/index.css
this PR makes many small improvements to scrollbar styling mostly on mobile and firefox
> Improved scrollbars

- src/constants/dungeons.js
- src/lib.js
- views/stats.ejs
- Changed constants for boss collections
- Updated boss collections to count tier completions
- Added option to max a boss collection
- Also added Sadan as a Floor 6 boss
> Updated Dungeons section (Boss Collections)

- views/stats.ejs
tbh my grammar fix is still prob shite but its better than the seizure the normal text gives me
> grammar fix

- public/resources/api/api_docs.json
Replaced API link from HTTP to HTTPS
> Update api_docs.json to replace API Docs's HTTP to HTTPS 

- public/resources/css/index.css
#98 only affected stats. This PR brings those changes to index
> add backdrop-filter blur to index

- public/resources/css/index.css
> remove old blur effect that was interfering with #110

- includes/resources.ejs
- public/resources/css/index.css
- views/stats.ejs
this fixes two similar problems to each having to do with scrollbars showing up where they shouldn't
in the process of fixing these bugs, I also redid the basic stats section so it uses grid layout now
> fix double scrollbars

- src/constants/pets.js
Added missing pet item "Spooky Cupcake"
https://sky.shiiyu.moe/stats/akiraplays/Pear
> support for pet item spooky cupcake

- src/constants/petStats.js
https://sky.shiiyu.moe/stats/dukioooo/Pomegranate
> Added missing stat for Mythic Bat pet (sea creature chance)

- src/constants/talismans.js
https://sky.shiiyu.moe/stats/ChayUwU/Orange
Before: https://i.imgur.com/r6A9SDY.png
After: https://i.imgur.com/CAAAuTh.png
> new accessories: pc7k and emerald ring

- src/constants/pets.js
> Fix: guardian is now an enchanting pet

- src/constants/pets.js
- src/lib.js
First commit fixes the random spaces in lib.js that just keep on appearing every time I try to edit that file... would appreciate if those could get fixed once and for all.
Some pets are mounts:
...in 2 commits cause in the first one I thought only horse and skeleton horse had "Mount"... wops
✦ added to pet name if the pet has a skin:
Support for future elephant skins:
- Pink: https://sky.shiiyu.moe/head/570eef474ec0e56cc34c2307eaa39f024612f8cd7248e7d5b14169ebd307c742
- Blue: https://sky.shiiyu.moe/head/4b62969c005815d0409136380febc5ac468aaba9bda4db80954fa5426ee0a323
- Orange: https://sky.shiiyu.moe/head/554a34a80c474206d3700b8fced6b44fab0b0ed0b05c1293ff0c5d86eda251d1
These last 3 skins will be available in ~18h 30min from this PR, so idk if you want to wait before merging 🤷‍♂️
> Pet fixes: "Mount" pets, ✦ in name if skin, upcoming elephant skins + fix spaces in lib.js

- views/index.ejs
Based on suggestion:
That suggestion also remembered me something I always found annoying while opening skycrypt... the main input not having autofocus, added that too.
Now when you open SkyCrypt you can type the ign you are looking for directly without having to click on the input first and your LastPass (or other password managers) won't try to autofill that input.
Preview:
> index main input id change and autofocus

- includes/resources.ejs
- public/resources/css/index.css
> Fix iOS item count Z fighting

- includes/resources.ejs
- views/index.ejs
- views/stats.ejs
- remove some Twitter-specific meta tags so that Twitter will fall back to the open graph tags
- fix `og:type` meta tag
- other small improvements
- escape HTML when possible because best practices
This PR may look a little confusing if you look at the files changed tab so look at each commit individually and it will be clear what it does.
> improve meta tags

- src/constants/pets.js
> Baby Yeti Grown-up skin

- views/stats.ejs
Currently best run shows the 10th best run
> Fix Best Runs

- includes/footer.ejs
> feat: synchronize theme across tabs

- includes/header.ejs
- includes/resources.ejs
- public/resources/css/index.css
- views/index.ejs
- views/stats.ejs
this PR updates the home page to use modern CSS layout patterns as well as a number of minor improvements and bug fixes related to the home page. 
- **the home page feels more polished**
- it is now easier to add and remove elements such as the SOL survey
-  the layout of the home page is flexible and dynamic making future changes easier
- the background blur weirdness on profiles has been fixed
- the home page is no longer letterboxed on iOS in landscape
- the developer badge is now a code icon instead of a laptop
- the search box no longer interrupts Keyboard shortcuts
- the weird green thing no longer appears in the address bar on iOS safari
- Windows Chrome
- Windows Firefox
- iOS Safari
- Android Chrome
> Improve home page

- public/resources/css/index.css
this PR has not been tested that is how confidant I am it will work
> fix: make error show on firefox

- src/constants/pets.js
Only blue tested, I can't find anyone with other colors to test them :/
> neon sheep skins [all tested now]

- views/index.ejs
> Make robots like googlebot stop indexing errors

- public/resources/css/index.css
> navbar fix for desktop

- public/resources/css/index.css
Fixed a bunch of things to make the website more responsive, now it should look good for devices with a resolution as small as 320px width.
I tested it for a bit and everything looks good to me but considering how the original css was written I wouldn't be surprised if something breaks at certain/specific resolutions....  
Example:
> CSS Responsive fix (supported up to 320px)

- src/constants/petStats.js
- src/constants/pets.js
- src/lib.js
> Mythic Jerry Pet

- includes/footer.ejs
- public/resources/js/stats.js
Checks that `playerModel` exists before executing any function requiring it
Not tested since I can't reproduce in local the issue found online:
> Attempt to fix skinViewer issue (tempfix), not tested

- src/constants/talismans.js
> Jerry talismans

- src/constants/petStats.js
Fixes missing formatting in a bunch of pets
> Fix missing format in pet stats

- src/constants/talismans.js
> Fix Jerry talismans

- src/constants/petStats.js
I know the branch is called pigman-fix, but it's actually for zombie.... 👀 
Just a missing `%`
> Missing % on zombie pet

- views/stats.ejs
> Recombobulated accessories stat

- src/lib.js
Updating constant MAX__SOULS from the old 209 fairy souls to the new 220 (11 from Dwarven Mines)
> Update max fairy soul count

- public/resources/css/index.css
Fixed bug as mentioned on #213 
Also fixed some design errors found in the same place (element centering and overlap elements)
> Fixed scrollbar on inventory view (#213)

- src/constants/pets.js
Skin: https://sky.shiiyu.moe/head/ca3a363368ed1e06cee3900717f062e02ec39aee1747675392255b48f7f83600
Releases at 18:00 GMT+1 today
> Silverfish Fossilized Skin

- src/constants/pets.js
> Zombie Skeleton horse skin 

- src/constants/petStats.js
I'm not sure about the modifyStats() since those stats have not been implemented yet....
> elephant and monkey pet fortune abilities

- includes/footer.ejs
- public/resources/js/stats.js
- public/resources/scss/index.scss
- src/constants/misc.js
- src/lib.js
- views/stats.ejs
Reverts SkyCryptWebsite/SkyCrypt#258
> Revert "Overhaul Inventory grid styling"

- views/index.ejs
this should have been done as part of #254 but I forgot
> increment discord logo version number

- src/constants/pets.js
> dragon pet skins

- includes/header.ejs
- includes/resources.ejs
- public/resources/html/offline.html
- public/resources/scss/api.scss
- public/resources/scss/index.scss
- public/search.osd
- src/app.js
- views/index.ejs
here are some of the effects of this PR:
- the search bars now use semantic HTML which leverages the browsers built-in features to provide a seamless accessible experiences
- the client-side now does some basic username/UUID checking to stop network calls from being made for obviously invalid usernames
- skycrypt now informs the browser that it is a search engine allowing users to search players without the need to open the skycrypt homepage
- spaces in usernames are now automatically replaced with underscores this will be especially useful on iOS where underscores are annoying to type
- several small CSS bug fixes
- code related to the random player feature has been commented out in a way that should prevent it from being sent over the wire saving on page size
> Better Search

- includes/header.ejs
- includes/resources.ejs
- public/resources/html/offline.html
- public/resources/scss/api.scss
- public/resources/scss/index.scss
- public/search.osd
- src/app.js
- views/index.ejs
Reverts SkyCryptWebsite/SkyCrypt#276
> Revert "Better Search"

- includes/header.ejs
- includes/resources.ejs
- public/resources/html/offline.html
- public/resources/scss/api.scss
- public/resources/scss/index.scss
- public/search.osd
- src/app.js
- views/index.ejs
This reverts commit 310c015ee4284b850c9c11ee16ee58f3e7d3c03b.
> Revert "Revert "Better Search""

- includes/footer.ejs
- includes/resources.ejs
- public/resources/js/stats.js
- public/resources/scss/index.scss
this PR makes some changes to `:focus` and the following visual change
> Improved profile name and keyboard accessibility

- includes/header.ejs
- includes/resources.ejs
- views/index.ejs
this PR fixes a bug where browsers will try to autofill email addresses in the "username" search bar
now the browser should only autofill things that you have previously typed into the search box
> fix username sugestions

- src/app.js
this PR removes an unused line of code that doesn't do anything
> remove unused favicon v2

- includes/footer.ejs
- includes/resources.ejs
- src/app.js
- src/hashes.js
this PR has 2 main benefits:
1. it fixes #286
2. it makes it so that we no longer have to increment version numbers for index.css or stats.js
> use File hash instead of version numbers

- includes/resources.ejs
this PR is basicly the same as #168
> use JSON.parse to improve performance

- views/stats.ejs
> fix catacombs skill bar

- public/resources/scss/index.scss
- views/stats.ejs
this PR enshures that the firefox background will always be in the same location as the chrome background
> fix firefox blurred background location

- src/helper.js
For misc -> claimed items
Tested (forgot to screenshot)
> Scorpius Bribe Year 120

- src/lib.js
This fixes the second problem in #275
> Fixed some crashing

- public/resources/scss/index.scss
- views/index.ejs
> remove extra 4px at bottom of profile links

- includes/header.ejs
- views/index.ejs
- views/stats.ejs
protect user privacy by requesting that the browser not infrom a website we link to what website the user is coming from
for more info see: https://web.dev/external-anchors-use-rel-noopener
> noreferrer

- public/resources/js/stats.js
- public/resources/scss/index.scss
> Inventory Sizing tweaks

- includes/resources.ejs
https://namemc.com/profile/g.2
https://namemc.com/profile/XH.1
> Allow searching for players with IGN shorter than 3 chars (examples: G, XH)

- public/resources/scss/index.scss
> remove star on stat icon

- public/resources/scss/index.scss
I finally found a way to reliably reproduce [this bug on discord](https://discord.com/channels/738971489411399761/738990246825427084/811578935459840030) and I fixed it using a suggestion from @dukio
> fix flickering on chrome

- src/lib.js
* Detection is now based on item ID, which is more reliable than using name, which could be localized
* Backpack data key detection is now slightly faster and cleaner
> refactor: Improved backpack data detection

- src/constants/talismans.js
Added personal deletor 4000 -> 7000
> personal deletor

- src/lib.js
updated max number of fairy soul from 220 to 222
> Updated max number of fairy souls

- src/constants/talismans.js
> reaper orb

- views/stats.ejs
Ok, I know this is kind of an useless PR... but seeing those uneven spaces was really triggering me :/
Before:
After:
> fix weight tooltip spaces

- views/stats.ejs
> add weight to og:description

- public/resources/js/stats.js
this PR includes a few minor improvements and fixes to the way stats are updating when switching weapons/fishing rods.
> fix stat updating

- src/constants/pets.js
> elephant monochrome

- src/constants/petStats.js
> fix pet zombie stats

- src/lib.js
Forgot to include pets in backpacks in my previous PR that includes pets from inventory and enderchest in the pets section.
> fix: pets from backpacks

- views/api.ejs
this PR fixes the problem described in #351 by reinitializing redoc when the theme is changed
> update api color on theme change

- includes/resources.ejs
- views/api.ejs
- views/index.ejs
- views/stats.ejs
move google tag code to resources to remove duplicate code and load critical rescorces first
> move google tag code to resources

- public/resources/scss/index.scss
this PR allows the browser to skip layout for some parts of the page until the user scrolls to them this should result in minor performance improvements when loading the page and resizing the browser window or changing device orientation.
> improve performance with content visibility

- public/resources/scss/index.scss
> fix overflow problem with basic stats

- src/lib.js
Reverts SkyCryptWebsite/SkyCrypt#356
> Revert "Rename certain mobs to reflect in-game names"

- includes/footer.ejs
flip jerries upside down on foolsday
note: this PR does not require a server restart
> flip some jerries

- src/constants/petStats.js
https://hypixel.net/threads/skyblock-0-11-3.4058260/
Fixes Lion, Skeleton, Spirit and Tiger
> Pet update

- src/lib.js
- views/stats.ejs
This PR aims to handle any possible weight error "NaN".
It checks the weight variable and if it is falsy it gives it the value -1.
The total weight only sums the valid (>= 0) values, so this can never be NaN now.
While printing, it checks if the weight value is valid and if it's not valid (not >= 0) is just says "Error"
I know it's not a super elegant solution, but it's 3am and I can't think of anything better right now.
PS: I used -1 because 0 could be a valid value
> Handle weight error "NaN"

- src/constants/pets.js
https://sky.shiiyu.moe/head/1bde55ed54cb5c87661b86c349186a9d5baffb3cb934b449a2d329e399d34bf
> baby chick skin

- src/constants/talismans.js
> dante talisman

- src/constants/misc.js
- src/helper.js
> make plus on VIP+ gold

- public/manifest.json
> add categories to web app manifest

- src/constants/pets.js
> fix baby chick

- views/stats.ejs
Adds a recap of all the reforges applied to the accessories (included "no reforge"). Useful if you want to copy a reforge setup from someone or if you want to check your own 😄
> accessories reforges

- views/stats.ejs
> Add total candies used stat to pets

- src/helper.js
this PR rewrites parseRank to be more modern, readable, and efficient.
code changes tested on the following players:
- Cookie_Wookie_7
- Zingo_Tealee
- Shiiyu
- FantasmicGalaxy
- Technoblade
- hypixel
- x_x
- NoxyD
> fix pig+++ plus color and refactor rank code

- src/constants/pets.js
> Rabbit Aquamarine + Rose skins

- public/resources/js/stats.js
- src/lib.js
- views/stats.ejs
this PR adds a way to compute time on the client and use the users own timezone
from now on all that needs to be done to add a localized time is:
```html
<local-time timestamp="<%= timestamp %>"></local-time>
```
- iOS has weird formating but it still displays the correct time I think this is just because iOS doesn't support some newer features yet because Apple sucks
- due to not knowing how hypixel handles daylight savings time the time for item obtaining is probably off by an hour about 25% of the time. I can do more experimenting next winter and should be able to fix this
iOS:
> Localize Time

- src/constants/talismans.js
Spiked crest and Blood God Crest
> spiked atrocity + blood god crest

- src/constants/misc.js
> mayor and minister ranks

- src/constants/misc.js
> cultivating X + harvesting VI

- public/resourcepacks/FurfSky_Reborn_1_2_5/config.json
> update FurfSky Reborn forum link

- src/constants/pets.js
> reaper gem pet item

- src/constants/pets.js
- views/stats.ejs
New black cat skins coming out later today and rewrote the old code that calculates total skins + user owned skins in views/stats.ejs
> Black cat skins and pet skins view rewrite

- src/constants/weight.js
- src/lib.js
+ Updated slayer weight calculation following Senither's change
+ Updated a comment about combat weight (was probably forgotted during last update)
Senither change (commit): https://github.com/Senither/Hypixel-Skyblock-Leaderboard/commit/96ec6ace89f23a461a953357fc44f45b6f1732af
> Update slayer weight calculation

- src/constants/dungeons.js
**Draft**: I'm currently trying to get them all, quest log doesn't say there's any more after these but I want to finish the last book to be sure about it.
> Updating catacombs journals

- views/stats.ejs
> highest floor beaten gold text

- src/constants/dungeons.js
> fix dungeons floor icon m6 m7

- public/resources/js/stats.js
- src/lib.js
- views/stats.ejs
> Separate talisman upgrades into upgradeable and non-upgradeable 

- public/resources/scss/index.scss
this is a temporary hotfix for a problem with pets that was exacerbated by #425
> fix: :ambulance: limit lore width to 500px

- src/constants/pets.js
> Flying Pig

- public/resources/scss/index.scss
this PR fixes https://discord.com/channels/738971489411399761/738990246825427084/839539130526203904
> fix golden slayer bars

- public/resources/scss/index.scss
- views/stats.ejs
before:
after:
in addition to fixing the above visual bug, this PR also refactors the progress bar css
> fix progress bar background

- src/lib.js
- views/stats.ejs
Previews:
(doesn't show on profiles without any legendary+ accessory)
> accessory enrichments

- src/constants/pets.js
Static skin until it's released, it will be an animated skin... I just can't obtain the animation without owning one :/
> Pet skin: Monkey Gorilla (static)

- views/stats.ejs
> add colon to best run grade

- src/constants/misc.js
> Support for GAME_MASTER

- src/lib.js
This fixes the lore popup of storage items in other sections like "Weapons".
> post-storage-item-popup-fix

- public/resources/scss/_stripes.scss
https://sass-lang.com/documentation/breaking-changes/slash-div
> remove deprecated use of `/` in sass stripes

- src/constants/petStats.js
> magma-cube-3rd-perk-nerf

- src/constants/pets.js
> Void Conqueror Enderman Skin

- src/constants/talismans.js
> patch 0.11.5 talismans

- src/helper.js
this PR refactors `getRawLore` to be more intuitive and I think this way is also slightly faster
> refactor getRawLore()

- index.js
- init.js
- src/api.js
- src/apiv2.js
- src/app.js
this PR uses prettier and eslint to format the core JS files in the sckycrypt backend
> format core js files with prettier

- public/resources/js/stats.js
this PR fixes all the linting errors in stats.js
> lint stats.js

- src/custom-resources.js
- src/hashes.js
- src/helper.js
- src/lib.js
- src/loreGenerator.js
- src/renderer.js
this PR uses eslint and prettier to format javscript files
> format helper js files with prettier

- init.js
- public/resources/fonts/icomoon/README.md
this PR does some prettier things that got missed in other PRs
> last prettier PR

- index.js
- src/apiv2.js
- src/app.js
- src/constants/leaderboards.js
- src/constants/petStats.js
- src/helper.js
- src/lib.js
this PR fixes some linting errors.
90% of this PR is cherry-picked from #449
> Final es-lint PR

- src/app.js
this PR forces cache only mode on when the hypixel status API says that the status of `Public API` is `under_maintenance`
it also puts a variable called `cacheOnly` on extra to allow future commits to indicate to the user that the site is in cache only mode
> add cacheonly mode

- public/resources/scss/index.scss
This PR fixes a non-critical css bug.
> make non-error banners work on firefox

- public/resources/scss/index.scss
> fix distorted heads

- public/resources/scss/index.scss
- views/stats.ejs
This PR removes Mixer from SkyCrypt
this was origanlay sugested on discord: https://discord.com/channels/738971489411399761/738990231348314123/843652813627719691
> remove Mixer

- src/api.js
- src/custom-resources.js
- src/helper.js
- src/lib.js
- views/stats.ejs
this PR refactors from
```js
someArray.filter(someCondition)[0]
```
to
```js
someArray.find(someCondition)
```
and from
```js
someArray.filter(someCondition).length > 0
```
to
```js
someArray.find(someCondition) != undefined
```
> refactor: :recycle: use find() instead of filter()[0]

- views/stats.ejs
I did a dumb in d9e4c89b8b2bfbbe956bc66db536fd7858c9bdb8 this PR fixes that
> critical fix syntax error in stats.ejs

- src/constants/weight.js
- src/lib.js
Adds support for enderman slayer in weight
Senither commit: https://github.com/Senither/Hypixel-Skyblock-Leaderboard/commit/a6355016be7c646b00bae6ca8f3ebbca99b157c4
Tested, it works:
- Senither's weight for my profile :https://hypixel-api.senither.com/v1/profiles/5435b597612f4554a3c651fd1c3ee96a/weight?key=XXX
- My profile after this PR: (same weight as senither)
> enderman slayer weight

- src/helper.js
> scorpius_bribe_144

- src/constants/pets.js
> dragon pastel

- views/stats.ejs
This PR makes a few fixes to enrichments
before:
after:
> Fix enrichments

- src/lib.js
this PR makes SkyCrypt ignore unknown collections instead of throwing
> ignore unknown collections

- src/constants/petStats.js
- src/constants/pets.js
This PR fixes the es-lint and prettier problems with the bal-pet branch
> Bal pet lint and style

- src/constants/petStats.js
- src/constants/pets.js
> Added Bal Pet

- src/constants/collections.js
- views/stats.ejs
close #610
This PR replaces the temporary red wool texture with the texture from the ~~ROUGH JASPER GEMSTONE~~ FINE JASPER GEMSTONE
> Gem collection texture

- src/constants/talismans.js
adds jungle amulet talisman to talisman list
> jungle amulet

- src/constants/talismans.js
> reorder jerry talismans

- src/constants/petStats.js
- src/lib.js
Adds 2 missing spaces and the "Mount" pet type
> Armadillo PR minor fixes

- src/constants/minions.js
> hard stone minion

- src/app.js
This PR makes app.js wait for `file-name-map.json` to exist before trying to read it
> Fix file name map doesn't exist yet

- src/constants/talismans.js
Fixes #624 
Power Talisman, Ring and Artifact
> power accessory

- src/helper.js
Basically the code was expecting a query with no results found to return `null`, while for me in localhost it returns `undefined` instead.
But why is it working with `null` on Nate PC and on the server? 🤔
> MongoDB error fix `TypeError: cannot read property 'date'/'last_updated' of undefined`

- src/loreGenerator.js
> fix tag error

- src/constants/petStats.js
> fix golden dragon stats

- src/helper.js
- src/loreGenerator.js
this PR adds comment using the [JSDoc](https://jsdoc.app/) standard which is suported by VS-Code and TypeScript
> Add some jsDoc comments

- src/helper.js
> refactor `calcDungeonGrade()`

- src/constants/misc.js
- src/helper.js
- src/lib.js
- src/loreGenerator.js
this PR primarily removed duplicated code
this PR also fixes #649
this PR also add jsdoc type comments to some functions
~~this PR should not be merged until it can be tested with a pet that modifies armor stats such as blaze~~
tested and working
> refactor lore stat updater and lore pirate name code

- src/helper.js
- src/lib.js
Closes #655. Shows applied gemstones to items in a nice way
> Gemstones in lore

- src/helper.js
this PR improves jsDocs and makes a very small refactor
> Gemstone lore Jsdoc

- public/resources/ts/globals.d.ts
- public/resources/ts/stats-defer.ts
- src/app.js
- views/stats.ejs
this fixes a thing @MartinNemi03 did
> allow stats to be cached between users with different favorites

- src/constants/misc.js
> fix crit damage

- src/constants/pets.js
> dark wolf skin

- src/lib.js
Gauntlet items have `equipmentType = none` and `type = gauntlet`.
`output.weapons` will include gauntlets
`output.pickaxes` will include gauntlets
...I thought this was gonna take a lot more time but... can it be this easy? am I missing something?
> gauntlet support

- public/resources/scss/index.scss
- public/resources/ts/browser-compat-check.ts
> improve update browser message on small screens

- src/constants/pets.js
> hound beagle skin

- src/constants/misc.js
```
master_diamond_guy: "Master Angry Archaeologist",
master_sadan_statue: "Master Terracotta",
master_tentaclees: "Master Fels",
maxor: "Necron",
```
Closes #742
> more mob_names fixes

- package-lock.json
- package.json
Reverts SkyCryptWebsite/SkyCrypt#774
> Revert "build(deps-dev): bump @typescript-eslint/parser from 4.29.3 to 4.30.0"

- package-lock.json
- package.json
Reverts SkyCryptWebsite/SkyCrypt#775
> Revert "build(deps-dev): bump typescript from 4.3.5 to 4.4.2"

- src/constants/pets.js
> beagle skin fix 🤦‍♂️

- src/constants/pets.js
When the skin drops I'll gather the animation data, but for now this can be merged
> glow squid

- src/constants/gemstones.js
- src/helper.js
Closes #801
- Updated gemstone stats using the ones posted by an admin [here](https://hypixel.net/threads/september-13th-crystal-hollows-patch.4544534/#post-32805668)
- the value "-1" for missing value is no longer useful so I removed it
- updated main comment
> Gemstone stats updated

- src/constants/misc.js
Added new special enchant Fortune 4 and also noticed Pristine 5 was missing
Closes #791
> special enchants pristine5 fortune4

- src/lib.js
I was quite sure I had already done this but.... clearly not 🤷‍♂️ 
Adds gauntlet in the skills>pickaxe section
> gauntlet in pickaxes

- src/constants/pet-stats.js
> Scatha update

- views/index.ejs
Moves it below the search, fixes the ❤ character and also makes it red.
> hc banner adjustments

- src/constants/gemstones.js
Adds values for flawless amber and jade gemstones in divine rarity
> flawless amber jade divine

- src/constants/talismans.js
> nether artifact

- .github/workflows/node.js.yml
lol not sure why this was still v1
> use v2 of checkout in CI

- src/constants/pet-stats.js
Removes console.log introduced here
https://github.com/SkyCryptWebsite/SkyCrypt/commit/16749bb096cb93b4214541100db9c04afad086c1
> pet skins gdrag console log

- src/constants/minions.js
With museum released a reward is Flower T12 minion, this PR adds that
Closes #923
> Flower t12

- public/resources/scss/shared.scss
- public/resources/ts/stats-defer.ts
- src/helper.js
- src/lib.js
Just a bunch of TODO comments clean-ups
> Todo comments clean-ups

- package-lock.json
- package.json
- src/weight/lilyWeight.js
this PR adapts to changes made in https://github.com/Antonio32A/lilyweight/pull/4
> upgrade lilyweight to 2.0.0

- src/constants/pet-stats.js
> Fix: blaze double hpb legendary only

- includes/resources.ejs
- public/resources/ts/common.ts
currently SkyCrypt gives this error
this PR fixes that by removing stuff that doesn't need to be on the global from the global
> remove stuff from global

- src/lib.js
Closes #848 
They are just not used anymore, no reason to keep them
> remove extra.anvil_uses

- src/helper.js
> scorpius bribe year 168

- src/custom-resources.js
Old code that has been commented for a while. Nate refactored this part a long time ago so it's no longer needed.
> remove custom resources leather color handler

- src/constants/hotm.js
I noticed I wasn't parsing the ints for hotm items id, damage values... woops
> fix: hotm itemdata parseint

- src/api.js
Closes #977 - see issue for more info.
> fix bazaar api

- public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/armor/dungeons/skeleton_master/skeleton_master_chestplate.properties
- public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/armor/dungeons/skeleton_master/skeleton_master_helmet.properties
- public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/armor/dungeons/skeleton_master/skeleton_master_layer_1.properties
> fix rnbw+ 0.7 dungeon skeleton_master

- src/constants/skins-animations.js
> PET_SKIN_PHOENIX_ICE

- src/constants/pet-stats.js
> fix bal stats

- src/constants/talismans.js
> bingo talis

- src/constants/misc.js
> Feather Falling XX

- src/constants/misc.js
- src/lib.js
fixes #858 
tested on AetherSword/Cucumber
> fix: show gauntlet in both weapons and pickaxes

- public/resources/ts/globals.d.ts
- src/lib.js
- src/weight/lily-weight.js
lily's discord bot:
before this PR:
after this PR:
> Fix lily weight

- public/resources/ts/globals.d.ts
- src/lib.js
this PR refactors `getLevelByXp` fixing some issues with XP and progress and adding comments so that not we know what is happening
> levels refactor

- src/lib.js
someone on discord said to increse max souls to 228
> Change max souls to 228

- src/constants/dungeons.js
- src/lib.js
- views/stats.ejs
See https://github.com/SkyCryptWebsite/SkyCrypt/pull/1053
> essence refactor

- src/app.js
this is a hotfix for this problem
> properly handle invalid parameters to the leather and potions endpoints
